version: "3.8"

services:
  mysql:
    build: .
    container_name: mysql-tutorial
    ports:
    - 3306:3306
    - 33060:33060
    volumes:
    - "./sql-scripts:/docker-entrypoint-initdb.d"
    - "./data:/var/lib/mysql"
